[tool.poetry]
name = "poetry-demo"
version = "0.0.0"
description = ""
authors = []
packages = [{include = "poetry_hello_world"}]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
