[tool.poetry]
name = "hs-mp-flight-gym"
version = "0.0.0"
description = ""
authors = []
packages = [{include = "hs_mp_flight_gym"}]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
